### ISSUE TITLE
Healthcheck not working

### ISSUE THREAD

**Issue by Taranys** [iam4x/bobarr#173]
Hi :)

Thanks for this project, it is really promising !

I found an issue when I tried to add `traefik` on docker-compose to manage a reverse-proxy and add plex. It didn't work well because Docker healthcheck is not working :
```
docker inspect --format "{{json .State.Health }}" bobarr-web

{"Status":"starting","FailingStreak":1,"Log":[{"Start":"2020-12-24T13:16:43.736731731Z","End":"2020-12-24T13:16:43.862622808Z","ExitCode":1,"Output":"/bin/sh: curl: not found\n"}]}
```

It seems that node-alpine do not contains curl :/

As a workaround, I disabled healthcheck and it works :
```
  web:
    container_name: bobarr-web
    image: iam4x/bobarr-web:latest
    healthcheck:
      disable: true
```
