### ISSUE TITLE
Completed downloads are not moved

### ISSUE THREAD

**Issue by darkmac78** [iam4x/bobarr#280]
Hi,

I have bobarr installed as a docker container with the following conf files:

env:
LIBRARY_MOVIES_FOLDER_NAME=movies
LIBRARY_TV_SHOWS_FOLDER_NAME=tvshows

docker-compose.yml:
  api:
    container_name: bobarr-api
    env_file: .env
    image: iam4x/bobarr-api:latest
    command: yarn start:prod
    restart: unless-stopped
    volumes:
      - /media/DATA-DISK/PLEX-SERVER:/usr/library
    ports:
      - 4000:4000

content of /media/DATA-DISK/PLEX-SERVER folder:
drwxr-xr-x 1 root root   0 Apr 23 15:55 movies/
drwxr-xr-x 1 root root  26 Apr 23 16:26 tvshows/

The container is started as root.

The issue is that the files are moved from library/downloads/incomplete/ to library/downloads/complete/ but not from library/downloads/complete/ to /media/DATA-DISK/PLEX-SERVER/tvshows.

The bobarr setting organize_library_strategy is set to Move

Am I missing something?

**Comment by ihasTaco** [comment]
I was having the same issue! heres what I found out, and how to fix it

The problem is that while Transmission can move files from incomplete to complete within the /library/downloads directory, bobarr-api needs access to this directory to move the files to their final location once they're finished.

To fix this, make sure the downloads folder is bound in the bobarr-api service like this:

`- ./library/downloads:/usr/library/downloads`

here is the full bobarr-api service 

```
services:
  api:
    container_name: bobarr-api
    env_file: .env
    image: iam4x/bobarr-api:latest
    command: yarn start:prod
    restart: unless-stopped
    volumes:
      - /media/DATA-DISK/PLEX-SERVER:/usr/library # where you want to the files to go
      - ./library/downloads:/usr/library/downloads # bind the downloads directory so the docker container can access it
    ports:
      - 4000:4000
```
